// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbhqmggvhfzqdpghqlyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiaHFtZ2d2aGZ6cWRwZ2hxbHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTcyNjUsImV4cCI6MjA3MTMzMzI2NX0.5yCksICgNOGMCPHKPvAO7GB97Jir3i-e4WuZryAiAqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});